[package]
name = "requeuest"
version = "0.1.0"
edition = "2018"
authors = ["Amanda Graven <amanda@amandag.net>"]
description = "Queue for HTTP requests using postgres as backing store"
readme = "README.md"

[dependencies]
base64 = "0.13"
http-serde = "1.0"
reqwest = { version = "0.11", default_features = false, features = ["rustls-tls"] }
sqlx = { version = "0.5", default_features = false, features = ["postgres", "chrono", "uuid", "runtime-tokio-rustls"] }
sqlxmq = { version = "0.1", default_features = false, features = ["runtime-tokio-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.6", features = ["sync", "parking_lot"] }
url = { version = "2", features = ["serde"] }
uuid = { version = "0.8", features = ["v4"] }

# Needed to avoid pulling in multiple versions, which breaks the build. It's of extra importance
# this dependency is kept up to date
webpki = "0.21"
